#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : go-github.com-inconshreveable-mousetrap
Version  : v1.0.0
Release  : 1
URL      : https://proxy.golang.org/github.com/inconshreveable/mousetrap/@v/list
Source0  : https://proxy.golang.org/github.com/inconshreveable/mousetrap/@v/list
Source1  : https://proxy.golang.org/github.com/inconshreveable/mousetrap/@v/v1.0.0.info
Source2  : https://proxy.golang.org/github.com/inconshreveable/mousetrap/@v/v1.0.0.mod
Source3  : https://proxy.golang.org/github.com/inconshreveable/mousetrap/@v/v1.0.0.zip
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: go-github.com-inconshreveable-mousetrap-data = %{version}-%{release}
BuildRequires : buildreq-golang

%description
# mousetrap
mousetrap is a tiny library that answers a single question.
On a Windows machine, was the process invoked by someone double clicking on
the executable file while browsing in explorer?

%package data
Summary: data components for the go-github.com-inconshreveable-mousetrap package.
Group: Data

%description data
data components for the go-github.com-inconshreveable-mousetrap package.


%prep

%install
rm -fr %{buildroot}
mkdir -p %{buildroot}/usr/share/goproxy/github.com/inconshreveable/mousetrap/@v
# Create list file using packaged versions
echo v1.0.0 >> %{buildroot}/usr/share/goproxy/github.com/inconshreveable/mousetrap/@v/list
install -m 0644 %{SOURCE1} %{buildroot}/usr/share/goproxy/github.com/inconshreveable/mousetrap/@v/v1.0.0.info
install -m 0644 %{SOURCE2} %{buildroot}/usr/share/goproxy/github.com/inconshreveable/mousetrap/@v/v1.0.0.mod
install -m 0644 %{SOURCE3} %{buildroot}/usr/share/goproxy/github.com/inconshreveable/mousetrap/@v/v1.0.0.zip


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/goproxy/github.com/inconshreveable/mousetrap/@v/list
/usr/share/goproxy/github.com/inconshreveable/mousetrap/@v/v1.0.0.info
/usr/share/goproxy/github.com/inconshreveable/mousetrap/@v/v1.0.0.mod
/usr/share/goproxy/github.com/inconshreveable/mousetrap/@v/v1.0.0.zip
